# wrangler.toml

name = "snoic"
compatibility_date = "2025-10-14"
pages_build_output_dir = "./dist/cloudflare"

# Only needed if your app (or one of your libraries) uses Node.js APIs
compatibility_flags = ["nodejs_compat"]

# Environment variables for local development
# For production, set these in Cloudflare Pages dashboard:
# Settings > Environment variables
[vars]
# DATABASE_URL = "postgresql://username:password@host:port/database"
[[kv_namespaces]]
  binding = "KV"  # 代码中使用的变量名
  id = "86bc502ddc244460bfbc7d77f15702b9"  # 从 Dashboard 复制
